version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Sobrescreve o host local para garantir conexão entre containers
      - DB_HOST=db
      - DB_PORT=5432
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendamento_consultas
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendamento_consultas"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    ports:

      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: always

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?} 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=ec2,logs,kms,s3,dynamodb,sts,iam
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-scripts:/etc/localstack/init/ready.d"
    restart: always

volumes:
  db_data:
  prometheus_data:
  grafana_data: